model_type: "hub_model"
local_dir: "./.qwen"
hub_url: "thiomajid/qwen1.5-moxe-baseline"
dataset_url: "EleutherAI/lambada_openai"
data_subset: "en"
data_split: "test"
text_column: "text"
batch_size: 32
max_seq_length: 256
num_workers: 4
samples: "all"
device: "cuda"
pin_memory: true
fp16: true
hub_token: null
