pad_token_id: 1
vocab_size: 49_152
context_length: 512
num_blocks: 12
embedding_dim: 768
slstm_at: []

mlstm_block:
  mlstm:
    conv1d_kernel_size: 4
    qkv_proj_blocksize: 32
    num_heads: 4

slstm_block:
  slstm:
    backend: "vanilla"
    num_heads: 4
    conv1d_kernel_size: 4
    bias_init: "powerlaw_blockdependent"
  feedforward:
    proj_factor: 1.7
    act_fn: "swish"
